### ISSUE TITLE
Infinite loop with `pad_uuid`

### ISSUE THREAD

**Issue by benkimpel** [gpedic/shortuuid#1]
It seems that `pad_uuid` will infinitely loop _seemingly_ when given a short uuid that becomes an integer larger than a certain size.

Examples...

```elixir
ShortUUID.decode("vurAvy8qYnp94isZcMSEPL") # Good
ShortUUID.decode("vurAvy8qYnp94isZcMSEPo") # Also, good
ShortUUID.decode("vurAvy8qYnp94isZcMSEPp") # Last character of p-z bad
```

And here's how each of those passes through steps in `decode` into `pad_uuid`...

```
Good
Input: "vurAvy8qYnp94isZcMSEPL"
Enum.reduce => 137256910693763254344733850037719112472
Integer.to_string => "6742B82D15634DB1B77FE1D2D4C79B18"

Good
Input: "vurAvy8qYnp94isZcMSEPo"
Enum.reduce => 338970767512771414526517954761987534011
Integer.to_string => "FF0365280EB0311FC6B2019237352CBB"

Bad
Input: "vurAvy8qYnp94isZcMSEPp"
Enum.reduce => 346441651098660605644361810492515994068
Integer.to_string => "104A23C27DF085F792F8DEFC8B61CC9D4"
```

Here's some logging from the loop...
```
[label: "uuid 104A23C27DF085F792F8DEFC8B61CC9D4"]                                                                     
[label: "uuid 0104A23C27DF085F792F8DEFC8B61CC9D4"]                                                                    
[label: "uuid 00104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 0000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 00000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 0000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 00000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 0000000000104A23C27DF085F792F8DEFC8B61CC9D4"] 
[label: "uuid 00000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 000000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 0000000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 00000000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
[label: "uuid 000000000000000104A23C27DF085F792F8DEFC8B61CC9D4"]
```

**Comment by benkimpel** [comment]
OH! @gpedic! I wasn't sure if this repo was still maintained... Glad to see you're around and hopefully you're healthy and safe from covid. I also had a patch for this issue if you'd like to take a look, but perhaps you can solve the issue better. https://github.com/gpedic/ex_shortuuid/pull/2

**Comment by gpedic** [comment]
Hey @benkimpel, thanks for pointing this out and also going through the trouble of investigating it too. It's a serious issue. 

Sometimes I miss things in the flood of notifications I get from github, will have to somehow highlight new issues/PRs.

I'm thinking to just go ahead and remove that function completely in favor of `String.pad_leading`, will push a PR soon

**Comment by benkimpel** [comment]
> Hey @benkimpel, thanks for pointing this out and also going through the trouble of investigating it too. It's a serious issue.

No problem. I like your solution better than the one I had, too. :+1:
